### ISSUE TITLE
Generic capabilitiy package name

### ISSUE THREAD

**Issue by LaDestitute** [Aurilux/Titles#23]
Hello, someone reported an incompatibility of your mod with my mod Z Arrows due to both of our capabilities using "capability" as the name of the package our capabilities were in, like so:
src/main/java/aurilux/titles/api/capability
src/main/java/ladestitute/zarrowsandstuff/util/capability

I fixed it on my end but I suggest as a precaution to change your capability package name to something less generic to prevent other mods from possibly causing crashes with Titles in the future.

**Comment by Aurilux** [comment]
I appreciate the heads up! However, may I see the error? This seems like an odd occurrence when our package names differ immediately after "src/main/java". I worry it may be something else.

**Comment by LaDestitute** [comment]
`[20Apr2021 19:55:55.646] [Server thread/ERROR] [net.minecraftforge.eventbus.EventBus/EVENTBUS]: Exception caught during firing event: com.ladestitute.zarrowsandstuff.util.capability.PlayerDataCapabilityFactory cannot be cast to aurilux.titles.api.capability.ITitles
	Index: 2
	Listeners:
		0: NORMAL
		1: ASM: class com.minecraftabnormals.environmental.common.item.explorer.ThiefHoodItem playerNameEvent(Lnet/minecraftforge/event/entity/player/PlayerEvent$NameFormat;)V
		2: ASM: class aurilux.titles.common.handler.CommonEventHandler onPlayerNameFormat(Lnet/minecraftforge/event/entity/player/PlayerEvent$NameFormat;)V
		3: ASM: mob_grinding_utils.events.ChickenFuseEvent@2772e3bb startChickenFuse(Lnet/minecraftforge/event/entity/living/LivingEvent;)V
		4: ASM: com.flemmli97.improvedmobs.events.EventHandler@1ac0fd3 pathDebug(Lnet/minecraftforge/event/entity/living/LivingEvent;)V
java.lang.ClassCastException: com.ladestitute.zarrowsandstuff.util.capability.PlayerDataCapabilityFactory cannot be cast to aurilux.titles.api.capability.ITitles
	at aurilux.titles.common.handler.CommonEventHandler$$Lambda$24509/112626366.accept(Unknown Source)
	at net.minecraftforge.common.util.LazyOptional.ifPresent(LazyOptional.java:165)
	at aurilux.titles.common.handler.CommonEventHandler.onPlayerNameFormat(CommonEventHandler.java:84)
	at net.minecraftforge.eventbus.ASMEventHandler_1261_CommonEventHandler_onPlayerNameFormat_NameFormat.invoke(.dynamic)
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85)
	at net.minecraftforge.eventbus.EventBus$$Lambda$2624/783182497.invoke(Unknown Source)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
	at net.minecraftforge.event.ForgeEventFactory.getPlayerDisplayName(ForgeEventFactory.java:260)
	at net.minecraft.entity.player.PlayerEntity.func_145748_c_(PlayerEntity.java:1757)
	at net.minecraft.entity.Entity.func_195051_bN(Entity.java:2641)
	at net.minecraft.command.Commands.func_197051_a(Commands.java:273)
	at net.minecraft.server.management.PlayerList.func_187245_a(PlayerList.java:597)
	at net.minecraft.server.management.PlayerList.func_187243_f(PlayerList.java:491)
	at net.minecraft.server.management.PlayerList.func_72355_a(PlayerList.java:162)
	at net.minecraft.network.login.ServerLoginNetHandler.func_147326_c(ServerLoginNetHandler.java:118)
	at net.minecraft.network.login.ServerLoginNetHandler.func_73660_a(ServerLoginNetHandler.java:65)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:222)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:134)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:865)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:118)
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642)
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232)
	at net.minecraft.server.MinecraftServer$$Lambda$23044/1150824238.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)`

**Comment by LaDestitute** [comment]
[latest.log](https://github.com/Aurilux/Titles/files/6347419/latest.log)
Here is the full log. I was told by a player who had several mods (+50!) in their Forge client installation, including our.

**Comment by Aurilux** [comment]
I just tested it with only our mods and I don't get the error. Ask him to verify the same thing. If it's not just our mods, ask them to disable/remove mods until they find out which one is the culprit. I would suggest they start with Minecraft Abnormals.

**Comment by LaDestitute** [comment]
Huh weird. I gave them an updated jar that fixed the crash on their end as I changed my capability folder name to "zarrowscap" and that fixed it as noted.

Should we then safely assume this is a weird edgecase and not a problem between our mods?

**Comment by Aurilux** [comment]
Yes, but I feel it could become a problem for them later on. Somewhere, something messed up and made everything fishy. There were tons of errors earlier in the log regarding the event bus. My best guess right now is that the actual problem happened there, and then cascaded to cause the error between our mods. Lots of other popular mods use the "capability" name for their folders, for example Botania, and I've never encounter an error like this one. I'll close this issue for now, but if you want to continue to discuss this feel free to message me on discord. There is a link to my server through my curseforge projects.
