### ISSUE TITLE
[Render thread/FATAL]: Error executing task on Client

### ISSUE THREAD

**Issue by CatastropheChou** [Aurilux/Titles#31]
Mod Version: Titles-1.16.5-3.4.1.jar
It didn't cause crash, but it would be nice if you can fix this fatal (log spamming made me annoyed) 
![image](https://user-images.githubusercontent.com/110756250/189153054-39d7f993-5863-422c-83aa-24457334c2c9.png)

https://pastebin.ubuntu.com/p/gxTYHZj8BC/

**Comment by Aurilux** [comment]
Looks like an easy fix. Thank you for letting me know!

**Comment by Aurilux** [comment]
Could you post more of the error log before the error gets triggered? An entire error log would be best. Just want to make sure this edge case gets properly handled.

**Comment by CatastropheChou** [comment]
Today I re-installed this mod into my pack and this FATAL turnsinto ERROR (
full log: https://pastebin.ubuntu.com/p/2fY9jckcfw/
java.lang.ClassCastException at Line 1016

**Comment by Aurilux** [comment]
Can you do me a favor and temporarily remove/disable Architectury (and whatever other mods rely on it) and see if this specific error disappears?

**Comment by CatastropheChou** [comment]
it doesn't disappear.
https://pastebin.ubuntu.com/p/NnSPyY7czM/
Line 1091

**Comment by CatastropheChou** [comment]
That's quite strange.
When I install this mod and Minecraft Forge 36.2.39 only, the errors do not appear.
When I install this mod in my 300 mods modpack, the Cast problem occurs.
I'll sift through the mods in the pack after dawn today, but I'm going to bed now.
Thank you.

**Comment by Aurilux** [comment]
No problem. If you figure out which mod, or mods, are causing the issue, let me know. Then I can look at the mod's code, if it's open source, so I can figure out a fix.

**Comment by Aurilux** [comment]
I was taking another look at the error log you posted, and it seems it doesn't like the "Renai Circulation" title. Is that a custom title that you've added?

**Comment by CatastropheChou** [comment]
No, I didn't any titles.

**Comment by Aurilux** [comment]
Ok, what mod adds plague asylums?

**Comment by CatastropheChou** [comment]
Hmmmmm     Today I installed this mod again into my modpack and the strange errors are gone.
I'm going to close this as the problem is now magically solved, thank you for your help.

**Comment by Aurilux** [comment]
Just wanted to let you know: the error was caused by the advancements in Dungeons Arise using plain text instead of a translatable lang entry for their advancement's title, i.e. "Renai's Circulation" instead of "advancements.plague_asylum.title" or something similar. I've made a test for it so it should no longer throw an error.

**Comment by Oli2004** [comment]
i just started to get this error when playing "Roguelike adventure and dungeons 2". i went to the twilight forest dimension and crashed, i try rejoining my server and the same thing happens. here is the fatal error from the debug.log



[25Jul2024 15:51:24.255] [Render thread/INFO] [mezz.jei.util.LoggedTimer/]: Starting JEI took 1.179 min
[25Jul2024 15:51:24.411] [Render thread/FATAL] [net.minecraft.util.concurrent.ThreadTaskExecutor/]: Error executing task on Client
java.lang.NullPointerException: null
	at aurilux.titles.common.core.TitleManager.getCapability(TitleManager.java:56) ~[titles:Titles-1.16.5-3.4.4.jar]
	at aurilux.titles.common.core.TitleManager.doIfPresent(TitleManager.java:52) ~[titles:Titles-1.16.5-3.4.4.jar]
	at aurilux.titles.common.core.TitleManager.setDisplayTitle(TitleManager.java:37) ~[titles:Titles-1.16.5-3.4.4.jar]
	at aurilux.titles.common.network.messages.PacketSyncAllDisplayTitles$1.run(PacketSyncAllDisplayTitles.java:50) ~[titles:Titles-1.16.5-3.4.4.jar]
	at net.minecraftforge.fml.network.NetworkEvent$Context.enqueueWork(NetworkEvent.java:201) ~[forge:?]
	at aurilux.titles.common.network.messages.PacketSyncAllDisplayTitles.handle(PacketSyncAllDisplayTitles.java:42) ~[titles:Titles-1.16.5-3.4.4.jar]
	at net.minecraftforge.fml.network.simple.IndexedMessageCodec.lambda$tryDecode$3(IndexedMessageCodec.java:114) ~[forge:?]
	at java.util.Optional.ifPresent(Optional.java:159) ~[?:1.8.0_422]
	at net.minecraftforge.fml.network.simple.IndexedMessageCodec.tryDecode(IndexedMessageCodec.java:114) ~[forge:?]
	at net.minecraftforge.fml.network.simple.IndexedMessageCodec.consume(IndexedMessageCodec.java:148) ~[forge:?]
	at net.minecraftforge.fml.network.simple.SimpleChannel.networkEventListener(SimpleChannel.java:66) ~[forge:?]
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.fml.network.NetworkInstance.dispatch(NetworkInstance.java:72) ~[forge:?]
	at net.minecraftforge.fml.network.NetworkHooks.lambda$onCustomPayload$1(NetworkHooks.java:77) ~[forge:?]
	at java.util.Optional.map(Optional.java:215) ~[?:1.8.0_422]
	at net.minecraftforge.fml.network.NetworkHooks.onCustomPayload(NetworkHooks.java:77) ~[forge:?]
	at net.minecraft.client.network.play.ClientPlayNetHandler.func_147240_a(ClientPlayNetHandler.java:1905) ~[?:?]
	at net.minecraft.network.play.server.SCustomPayloadPlayPacket.func_148833_a(SCustomPayloadPlayPacket.java:59) ~[?:?]
	at net.minecraft.network.play.server.SCustomPayloadPlayPacket.func_148833_a(SCustomPayloadPlayPacket.java:11) ~[?:?]
	at net.minecraft.network.PacketThreadUtil.func_225383_a(SourceFile:21) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) ~[?:?]
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213160_bf(SourceFile:103) ~[?:?]
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:948) ~[?:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) ~[?:?]
	at net.minecraft.client.main.Main.main(Main.java:184) ~[1.16.5.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_422]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_422]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_422]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_422]
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:37) ~[forge-1.16.5-36.2.39.jar:36.2]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.1.3.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.1.3.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.1.3.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.1.3.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.1.3.jar:?]
[25Jul2024 15:51:24.419] [Render thread/WARN] [net.minecraft.client.network.play.ClientPlayNetHandler/]: Unknown custom packet identifier: spawnermod:main
[25Jul2024 15:51:24.422] [Render thread/INFO] [net.mehvahdjukaar.supplementaries.Supplementaries/]: Synced Globe data



the game also exits with this error code: -1073741819

**Comment by Oli2004** [comment]
due to the size of the debug.log i had to upload it else where: https://gofile.to/eBA/debug-1.log

**Comment by Aurilux** [comment]
Looks like a conflict between Titles and another mod, but I can't tell which one. You can use the steps described here to try to identify which one: https://github.com/Aurilux/Titles/wiki#game-crashing. Beyond that, I am unable to update such an old version of Titles as my time must go to more modern versions.
